CREATE TABLE roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    permission JSON NULL DEFAULT NULL,
    createdBy INT NULL DEFAULT NULL,
    updatedBy INT NULL DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO roles 
(name, slug, status, permission, createdAt, updatedAt) 
VALUES
('Admin', 'admin', 'active', '{"employee": {"add": true, "allView": true, "ownView": true, "edit": true, "delete": true}, "customer": {"add": true, "allView": true, "ownView": true, "edit": true, "delete": true}}', NOW(), NOW()),
('Manager', 'manager', 'active', '{"employee": {"add": true, "allView": true, "ownView": true, "edit": true, "delete": false}, "customer": {"add": true, "allView": true, "ownView": true, "edit": true, "delete": true}}', NOW(), NOW()),
('Employee', 'employee', 'active', '{"employee": {"add": false, "allView": false, "ownView": true, "edit": false, "delete": false}, "customer": {"add": true, "allView": false, "ownView": true, "edit": true, "delete": false}}', NOW(), NOW());

CREATE TABLE employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    manager_id INT NULL DEFAULT NULL,
    identity VARCHAR(100) NOT NULL,
    image VARCHAR(200) NULL DEFAULT NULL,
    department VARCHAR(300) NOT NULL,
    team VARCHAR(200) NULL DEFAULT NULL,
    gender ENUM('male', 'female', 'other') NULL DEFAULT 'male',
    blood_group VARCHAR(50) NULL DEFAULT NULL,
    label_color VARCHAR(50) NULL DEFAULT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    designations VARCHAR(500) NOT NULL,
    mobile VARCHAR(15) NOT NULL,
    work_shift VARCHAR(100) NOT NULL,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    work_location VARCHAR(200) NOT NULL,
    type VARCHAR(100) NOT NULL,
    emp_type VARCHAR(100) NOT NULL,
    business_unit VARCHAR(200) NOT NULL,
    license VARCHAR(100) NOT NULL,
    cost_center VARCHAR(100) NOT NULL,
    role_id INT NOT NULL,
    app_version VARCHAR(50) NOT NULL,
    desktop_version VARCHAR(50) NOT NULL,
    last_desktop_started_at DATETIME NOT NULL,
    last_Sync_desktop_at DATETIME NOT NULL,
    last_Sync_mobile DATETIME NOT NULL,
    last_location VARCHAR(200) NOT NULL,
    location VARCHAR(200) NOT NULL,
    address VARCHAR(500) NOT NULL,
    date_of_birth DATETIME NOT NULL,
    date_of_joining DATETIME NOT NULL,
    state_id INT NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    region_id INT NOT NULL,
    branch_id INT NOT NULL,
    password VARCHAR(200) NOT NULL,
    refreshToken TEXT NULL DEFAULT NULL,
    createdBy INT NULL DEFAULT NULL,
    updatedBy INT NULL DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_employees_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE offices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    address VARCHAR(500) NOT NULL,
    state_id VARCHAR(200) NOT NULL,
    region_id VARCHAR(200) NOT NULL,
    branch_id VARCHAR(200) NOT NULL,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    latitude FLOAT(9) NOT NULL,
    longitude FLOAT(10) NOT NULL,
    radius FLOAT(6) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NULL DEFAULT NULL,
    phone VARCHAR(20) NULL DEFAULT NULL,
    slug VARCHAR(200) NULL DEFAULT NULL UNIQUE,
    owner INT NULL DEFAULT NULL,
    location VARCHAR(500) NULL DEFAULT NULL,
    district VARCHAR(200) NULL DEFAULT NULL,
    state VARCHAR(200) NULL DEFAULT NULL,
    sub_state VARCHAR(200) NULL DEFAULT NULL,
    branch_code VARCHAR(100) NULL DEFAULT NULL,
    branch VARCHAR(200) NULL DEFAULT NULL,
    center VARCHAR(200) NULL DEFAULT NULL,
    center_code VARCHAR(100) NULL DEFAULT NULL,
    loanType VARCHAR(100) NULL DEFAULT NULL,
    loanNo VARCHAR(100) NULL DEFAULT NULL,
    oldLoanNo VARCHAR(100) NULL DEFAULT NULL,
    oldCustomerNo VARCHAR(100) NULL DEFAULT NULL,
    image TEXT NULL DEFAULT NULL,
    cycle INT NULL DEFAULT NULL,
    loanDisbDate DATE NULL DEFAULT NULL,
    loanAmount DECIMAL(12, 2) NULL DEFAULT NULL,
    os_principal DECIMAL(12, 2) NULL DEFAULT NULL,
    os_interest DECIMAL(12, 2) NULL DEFAULT NULL,
    par INT NULL DEFAULT NULL,
    od_principal DECIMAL(12, 2) NULL DEFAULT NULL,
    od_interest DECIMAL(12, 2) NULL DEFAULT NULL,
    totalDueAmount DECIMAL(12, 2) NULL DEFAULT NULL,
    total_principal_collectible DECIMAL(12, 2) NULL DEFAULT NULL,
    total_interest_collectible DECIMAL(12, 2) NULL DEFAULT NULL,
    irrRate DECIMAL(5, 2) NULL DEFAULT NULL,
    noOfInstallment INT NULL DEFAULT NULL,
    lastDueDate DATE NULL DEFAULT NULL,
    lastPaidTrxDate DATE NULL DEFAULT NULL,
    dpd INT NULL DEFAULT NULL,
    paidInstNo VARCHAR(50) NULL DEFAULT '0',
    loanStatus VARCHAR(50) NULL DEFAULT 'Open',
    spouseName VARCHAR(200) NULL DEFAULT NULL,
    installmentAmount DECIMAL(12, 2) NULL DEFAULT NULL,
    maturityDate DATE NULL DEFAULT NULL,
    pincode VARCHAR(20) NULL DEFAULT NULL,
    preClosureAmt DECIMAL(12, 2) NULL DEFAULT NULL,
    closedDate DATE NULL DEFAULT NULL,
    createdBy INT NULL DEFAULT NULL,
    updatedBy INT NULL DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_customers_owner FOREIGN KEY (owner) REFERENCES employees (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    taskType VARCHAR(200) NOT NULL,
    customerId INT NOT NULL,
    description VARCHAR(500) NOT NULL,
    priority VARCHAR(200) NULL DEFAULT NULL,
    assigneeToEmployeeId INT NULL DEFAULT NULL,
    startDateTime DATETIME NULL DEFAULT NULL,
    endDateTime DATETIME NULL DEFAULT NULL,
    `repeat` TINYINT(1) NULL DEFAULT NULL,
    frequency ENUM('hour', 'day', 'week', 'month', 'year') NULL DEFAULT NULL,
    `interval` INT NULL DEFAULT NULL,
    time TIME NULL DEFAULT NULL,
    payment_type DECIMAL(12, 2) NULL DEFAULT NULL,
    additionalFields JSON NULL DEFAULT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    createdBy INT NULL DEFAULT NULL,
    updatedBy INT NULL DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_tasks_customer FOREIGN KEY (customerId) REFERENCES customers (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_tasks_assignee FOREIGN KEY (assigneeToEmployeeId) REFERENCES employees (id) ON DELETE SET NULL ON UPDATE CASCADE
);
